### PR TITLE
created about us page

### PR DESCRIPTION
**Pull request by oluwafunmilola99**
***what is this pull-request about?***
this is About Us page.

***Details of this Feature.***
-created About me page
-Added images of the team members in size and square shape
-Added it on the sidebar
***snapshots of the code***
-vscode_snapshot

-result of About us page

### CODE REVIEW

**Comment by oluwafunmilola99** [comment]
i created this work

**Comment by oluwafunmilola99** [comment]
team member checkout my work

**Review by Redux23 — APPROVED** [review]
Pull request approved

**Comment by oluwafunmilola99** [comment]
thank you bright

**Pull request merged**
